### ISSUE TITLE
Not Working in Android 2.3 (TypeError undefined is not a function)

### ISSUE THREAD

**Issue by atulrungta** [brody2consult/cordova-sqlite-storage#283]
.factory('sqlhelper', function ($cordovaToast, $cordovaSQLite, $q) {
    try {
        var db = null;
        return {
            registerdb: function () {
                var def = $q.defer();
                try {
            db = $cordovaSQLite.openDB('someapp.db');
                    $cordovaSQLite.execute(db, "CREATE TABLE IF NOT EXISTS tblappsetting (countrycode text, mobilenumber text, firstname text, lastname text, email text, gender text, dateofbirth text, profilepic blob, lasttoken text, devregid text, activestatus integer, devplatform integer)");
                    $cordovaSQLite.execute(db, "CREATE TABLE IF NOT EXISTS tblgroupmast (id integer not null primary key autoincrement, grpuserid integer not null, grptitle text not null, grpimg blob not null, grpdesc text null, lastupdated text not null)");
                    $cordovaSQLite.execute(db, "CREATE TABLE IF NOT EXISTS tblnotificationmast (id integer not null primary key autoincrement, grpid integer not null, msgid integer not null,msguuid text not null, msguid text not null, senttime text not null, receivetime text not null, receivestatus integer null, readtime text null, readstatus integer null, msgtype integer not null, msgcontent text not null, msgsize integer not null, msgremark text null, msgdwnld integer not null)");
                    $cordovaSQLite.execute(db, "CREATE UNIQUE INDEX tblgroupmast_idx ON tblgroupmast(id, grpuserid)");
                    $cordovaSQLite.execute(db, "CREATE UNIQUE INDEX tblnotificationmast_idx ON tblnotificationmast(id, msguuid)");
                    def.resolve(true);
                } catch (e) {
                    $cordovaToast.showLongCenter("ERROR 10001"+e);
                    def.reject(e);
                }
                return def.promise;
            },
            execute: function (query, params) {
                var def = $q.defer();
                try {
                    if (db == null) {
                                               db = $cordovaSQLite.openDB('notibellapp.db');
                    }
                    if (params == null) {
                        $cordovaSQLite.execute(db, query).then(function(res) {
                            def.resolve(res);
                            return res;
                        }, function (err) {
                            def.reject(err);
                        });
                    }
                    else {
                        $cordovaSQLite.execute(db, query, params).then(function(res) {
                            def.resolve(res);
                            return res;
                        }, function (err) {
                            def.reject(err);
                        });
                    }
                } catch(e) {
                    $cordovaToast.showLongCenter("ERROR 10002"+e);
                    def.reject(e);
                }
                return def.promise;
            }
        }
    } catch (e) {
        $cordovaToast.showLongCenter("ERROR 10003"+e);
    }
})

Above is my factory for sqlite. Below is code in a controller where I call registerdb.

$ionicPlatform.ready(function() {
            sqlhelper.registerdb().then(function () {
                push.registerPush().then(function () {});
                settingshelper.getall().then(function (res) {
                    if (res.rows.length > 0) {
                        var allsetting = res.rows.item(0);
                        if (allsetting != null) {
                            if (allsetting.lasttoken != null && allsetting.activestatus != null) {
                                if (allsetting.activestatus == false || allsetting.activestatus == 'false') {
                                    $scope.regconfirm();
                                }
                                else {
                                    if (allsetting.firstname == null || allsetting.firstname == ' ') {
                                        $scope.userprofile();
                                    }
                                    else {
                                        $scope.notifications();
                                    }
                                }
                            }
                            else {
                                $scope.register();
                            }
                        }
                        else {
                            $scope.register();
                        }
                    }
                    else {
                        $scope.register();
                    }
                }, function (err) {
                    $cordovaToast.showLongCenter("ERROR 1004: " + err);
                });
            });
        });

While registering device for push notifications when device registeration id is given by GCM i call following code from another factory:

setregid: function (regid) {
            try {
                sqlhelper.execute("SELECT \* FROM tblappsetting;", null).then(function (res) {
                    if (res.rows.length > 0) {
                        sqlhelper.execute("UPDATE tblappsetting SET devregid=?;", [regid]);
                    }
                    else {
                        sqlhelper.execute("INSERT INTO tblappsetting (devregid) VALUES (?);", [regid]);
                    }
                });
            } catch (e) {
                $cordovaToast.showLongCenter("ERROR 1005: " + e);
            }
        }

Whole App is working fine in devices having android 4.x but when I tested same apk file on 2.3 then it does not work.

**Comment by nolanlawson** [comment]
It would be more helpful if you could offer a sample app so that we could test it out. :) Else a stacktrace that says exactly which function is undefined would be useful too.

9 times out of 10, this is due to some ES5 syntax not being available in Android 2.3 (e.g. Function.prototype.bind), so you could fix it by including the es5-shim: https://github.com/es-shims/es5-shim
