### ISSUE TITLE
Cordova SQLIte Plugin Not Working on Windows Phone 8.1

### ISSUE THREAD

**Issue by sachin123sharma** [brody2consult/cordova-sqlite-storage#248]
HI Team ,

I am having Hybrid app for Windows, We are Using Cordova 3.5 ,SQLitePlugin By Cordova , We had created this Project on Windows 8.0 , But We also need to execute app on 8.1 Windows phone. So we Retarget the app to Windows 8.1 .

Now The issue is WE are not able to Execute the app on 8.1 ,If we comment out code which is using SQLItePlugin (SQL create statement) , Application Gets Loaded. So We tried with New SQLite Plugin , but the application gets crashed (259 exit error code). 
Please suggest some solution.

Thanks in advance.

**Comment by brody2consult** [comment]
Can you please specify whether you running the windows or wp8 target (both should work on Windows Phone 8.1)?

The windows version targets Windows 8.1 and Windows Phone 8.1. If you need to target Windows 8.0, it needs another vcxproj file (which I cannot create since I am using Visual Studio Express 2013). If you need to target all three Windows 8.0, Windows 8.1, and Windows Phone 8.1, please let me know and I can give you some pointers.

**Comment by sachin123sharma** [comment]
Target is Windows Phone 8.1

**Comment by brody2consult** [comment]
Yes but which Cordova target platform ID did you use: `windows` or `wp8`?

**Comment by sachin123sharma** [comment]
WP 8

**Comment by brody2consult** [comment]
For Windows Phone 8.1, I suggest you make a Windows Universal app instead (which is supported by the Cordova `windows` target). The Windows (Universal) version of this plugin uses the C++ SQLite3-WinRT library to connect the Javascript with sqlite 3.8.9 which is much more stable, while the wp8 version uses CSharp-SQLite which has some known stability issues. Instructions are in README.md.

**Comment by sachin123sharma** [comment]
I tried making a Windows Universal app and adding C++ Sqliite3-WinRT as suggested. But while deploying the app to windows 8.1 device, it gives error:

 "Error1    The processor architecture of your project 'arm' doesn’t match the processor architecture 'x86' of the referenced project 'SQLite3Component'. Change the targeted processor architectures to align between your project and its references"

If I change the architecture from 'ARM' to 'x86', I cannot deploy it to device (as then only emulator option is available ). Moreover it gives another error: "Error    4   Error : DEP0001 : Unexpected Error: The operation attempted to access data outside the valid range (Exception from HRESULT: 0x8000000B)"

Please suggest.

**Comment by brody2consult** [comment]
Which vcxproj file(s) did you include?

Please make sure that you include the vcxproj files that you see for the `windows` target in plugin.xml.

NOTE: SQLite3-Windows8.1.vxcproj is old and _WILL NOT WORK_ with Windows Phone.

Please try it again with a fresh, clean project _without any of your company data in it_. If it (still) does not work then please post a copy of it for me or send it to info@litehelpers.net

**Comment by sachin123sharma** [comment]
We Have downloaded SQLite3 from https://github.com/doo/SQLite3-WinRT link and using this. Our project is not having plugin.xml. Please suggest us, are we on right track?

**Comment by brody2consult** [comment]
> We Have downloaded SQLite3 from https://github.com/doo/SQLite3-WinRT link
> and using this. Our project is not having plugin.xml. Please suggest us, are
> we on right track?

Nope! All you have to do is use the Cordova CLI or plugman tool to include this plugin, and you can build it for Windows (8.1) or Windows Phone 8.1. Some notes in the next comment.

**Comment by brody2consult** [comment]
I am getting ready to go on vacation in Poland for almost a week, with limited connectivity. But I really want to see the new Windows "Universal" version working for you.

It is highly recommended to use `plugman` to include this plugin, as described in README.md.

If you _do_ want to try using the Cordova CLI, please use the following command to get the latest version: `cordova plugin add io.lihttps://github.com/litehelpers/cordova-sqlite-common`

**Comment by sachin123sharma** [comment]
Thanks, it helped. We were able to install the plugin you mentioned using Cordova CLI. We created a new project with CLI only and installed this plugin.

**Comment by sachin123sharma** [comment]
When i tried with the sample code given here it is giving the following error.

OPEN database: my.db
db name: my.db at full path: C:\Data\Users\DefApps\APPDATA\Local\Packages\com.SVM.DR.Beta_bzbj8h50hftv4\LocalState\my.db
new transaction is waiting for open operation
OPEN database: my.db failed, aborting any pending transactions

Are we missing anything??

**Comment by brody2consult** [comment]
Windows or Windows Phone? Emulator or device?

Looks like something went wrong with your installation. I tested it mostly using `plugman` to install and suggest you try the same.

If you continue to have problems please post your project or send it to me brodybits@litehelpers.net and I can take look later today or tonight.

**Comment by sachin123sharma** [comment]
Windows phone.
I am sending you the project (sample),which I created using CLI, to your email id. Would appreciate if you could look  at it and guide.

**Comment by brody2consult** [comment]
Unfortunately I do not see your project.

**Comment by sachin123sharma** [comment]
Please check your email now. The code link has been shared.

**Comment by brody2consult** [comment]
I see it now. For a sample (test), please look at the Quick installation test on README.md and follow the directions how to make the Windows Universal project using `plugman`.

**Comment by sachin123sharma** [comment]
We followed the steps of creating a project using Plugman. 
We got following error while building the project:
fatal error C1083: Cannot open source file: 'D:\SVN_DR_with_plugman\cordova\plugins\cordova-sqlite-common\src\external\sqlite3.c

Please guide.

**Comment by brody2consult** [comment]
> We followed the steps of creating a project using Plugman.
> We got following error while building the project:
> fatal error C1083: Cannot open source file: 'D:\SVN_DR_with_plugman\cordova\plugins\cordova-sqlite-common\src\external\sqlite3.c

`cordova-sqlite-common` is there for development and testing purposes. Please start again with a fresh project and add this version: https://github.com/litehelpers/Cordova-sqlite-storage

**Comment by sachin123sharma** [comment]
Finally, this plugin worked. Thanks :)

**Comment by brody2consult** [comment]
On Apr 29, 2015 2:40 PM, "sachin123sharma" notifications@github.com wrote:

> Finally, this plugin worked. Thanks :)

:+1: Happy to hear!

**Comment by sachin123sharma** [comment]
:-) Thanks....

**Comment by sachin123sharma** [comment]
:+1:

**Comment by sachin123sharma** [comment]
Hi Chris ,
Need your help ..

We have hybrid app , and we are using cordova-sms-plugin for Windows phone 8.0 app it works fine with 8.0 , But as we moved to windows phone 8.1 , this plugin is not working.

Please can you suggest.

THanks,
 Sachin Sharma

**Comment by brody2consult** [comment]
> We have hybrid app , and we are using cordova-sms-plugin for Windows
> phone 8.0 app it works fine with 8.0 , But as we moved to windows phone 8.1
> , this plugin is not working.

Do you mean that the SMS plugin does not work on windows phone 8.1, or is
there an issue with this plugin?

**Comment by sachin123sharma** [comment]
Previous we created app using cordova template for windows phone 8.0. In that sms plugin (cordova-sms-plugin) was working fine which has a "sms.cs" native implementation.

Now, when created app using plugman, we are unable to use the same plugin for sms. Reason may be that it is c# code and plugman uses VC+ code. 
Could you please suggest sms plugin for windows phone 8.1 app which works along with plugman installation?
Need your help to resolve this critical issue.

**Comment by brody2consult** [comment]
On Apr 30, 2015 5:57 PM, "Chris Brody" chris.brody@gmail.com wrote:

> > We have hybrid app , and we are using cordova-sms-plugin for Windows
> > phone 8.0 app it works fine with 8.0 , But as we moved to windows phone 8.1
> > , this plugin is not working.
> 
> Do you mean that the SMS plugin does not work on windows phone 8.1, or is
> there an issue with this plugin?

Unfortunately the Cordova SMS plugin does not support our windows
("universal ") target. I found the following answer on Stack Overflow how
to work with SMS on Windows Phone 8.1:
http://stackoverflow.com/questions/23555640/make-a-phone-call-in-windows-phone-8-1

I am writing this in a tour bus in Poland right now. I can try to make the
new windows phone 8.1 version later tonight if you want to test it for me.

Chris

**Comment by brody2consult** [comment]
To send an SMS in Windows Phone 8.1, adapt the following Javascript code:

``` Javascript
var cm = new Windows.ApplicationModel.Chat.ChatMessage();
cm.body = "test 1";
cm.recipients[0]="1234567";
Windows.ApplicationModel.Chat.ChatMessageManager.showComposeSmsMessageAsync(cm);
```

I already raised cordova-sms/cordova-sms-plugin#31 for discussion. I would prefer to integrate this into the cordova-sms-plugin after I return from vacation. Note that this will not work for Windows 8.0/8.1, you have to use Windows.Devices.Sms.SmsDevice.

Another issue with this solution is that even when the user sends the message, the SMS composer stays until the user explicitly leaves the SMS composer (perhaps by using the back button). ~~Please report if this will be problem for you.~~ _This is also true of the cordova-sms-plugin._

**Comment by brody2consult** [comment]
Also, if you need a callback upon (successful) completion, change the last line of the Javascript I gave you to something like this:

``` Javascript
Windows.ApplicationModel.Chat.ChatMessageManager.showComposeSmsMessageAsync(cm).done(function() {
    // handle success here
});
```

**Comment by brody2consult** [comment]
On Apr 30, 2015 6:06 PM, "sachin123sharma" notifications@github.com wrote:

> Previous we created app using cordova template for windows phone 8.0. In
> that sms plugin (cordova-sms-plugin) was working fine which has a "sms.cs"
> native implementation.
> 
> Now, when created app using plugman, we are unable to use the same plugin
> for sms. Reason may be that it is c# code and plugman uses VC+ code.
> Could you please suggest sms plugin for windows phone 8.1 app which works
> along with plugman installation?
> Need your help to resolve this critical issue.

Did you have a chance to try my suggestion? I am only available for a few
more hours today and not available tomorrow due to sabbath.

**Comment by brody2consult** [comment]
Hi I will probably work on the SMS plugin sometime next week. Did you have a chance to try my suggestion above?

**Comment by sachin123sharma** [comment]
Hay Chris ,
Sorry for delay in reply . The suggested solution for SMS Plugin Works for Wuindows Phone 8.1 .

Thanks a Lot !!! Cheers !!!
Thanks,
Sachin Sharma

**Comment by brody2consult** [comment]
> The suggested solution for SMS Plugin Works for Wuindows Phone 8.1 .

:+1: Very happy to hear!

Will issue PR to integrate this into the official SMS plugin when I get a
chance. May be a few weeks.

**Comment by aorfevre** [comment]
Hi Chris,

I'm alreay a user of your plugin for Android & iOS and it is working perfectly so far.

It's been several days that I'm trying to implement this great plugin for WindowsPhone 8.1.

I have been testing various solution and finally ended with a solution that let me compile & run for windows phone 8.1.
I'm using following command : cordova run windows --device --archs="arm" -- -phone

I'have done a basic test (open DB & write to DB) and it seems to work.

My issue is that now, I want to debug my app and I don't know / can't deploy it from visual studio.
\plugins\io.litehelpers.cordova.sqlite\src\windows\SQLite3-WinRT\SQLite3\Database.cpp(34): warning C4244: 'return' : conversion de 'sqlite3_int64' en 'int', perte possible de données C:\Users\Alexandre\Desktop\RIZZE\IONIC\rzIonic\plugins\io.litehelpers.cordova.sqlite\src\windows\SQLite3-WinRT\SQLite3\SQLite3.WindowsPhone.vcxproj]

## I'll mail you all my current study if you'd like to see.

FINALLY, I SUCCEEDED to have debug mode too;  but I needed to :
- open Visual Studio
- remove reference of SQLite.phone
- Add existing project (plugins/sqlite)
- Add reference to project

I'll be waiting for a better solution for the futur, but for instance, this does the trick !
Thank you for this great plugin !

**Comment by brody2consult** [comment]
> I'm alreay a user of your plugin for Android & iOS and it is working
> perfectly so far.

:+1:

> It's been several days that I'm trying to implement this great plugin for
> WindowsPhone 8.1.
> 
> I have been testing various solution and finally ended with a solution
> that let me compile & run for windows phone 8.1.
> I'm using following command : cordova run windows --device --archs="arm"
> -- -phone

Yes that is correct. Will be documented when I get a chance.

> My issue is that now, I want to debug my app and I don't know / can't
> deploy it from visual studio.
> 
> \plugins\io.litehelpers.cordova.sqlite\src\windows\SQLite3-WinRT\SQLite3\Database.cpp(34):
> warning C4244: 'return' : conversion de 'sqlite3_int64' en 'int', perte
> possible de données
> C:\Users\Alexandre\Desktop\RIZZE\IONIC\rzIonic\plugins\io.litehelpers.cordova.sqlite\src\windows\SQLite3-WinRT\SQLite3\SQLite3.WindowsPhone.vcxproj]

To fix this will have to use something like `long int` (`long`) for
`Database::LastInsertRowId`. It is also brute-force it with a cast (which
is probably a pretty bad idea).

> I'll mail you all my current study if you'd like to see.

Thanks, saw your mail and really appreciate your offer to help!

> FINALLY, I SUCCEEDED to have debug mode too; but I needed to :
> 
> open Visual Studio
> remove reference of SQLite.phone
> Add existing project (plugins/sqlite)
> Add reference to project

I did not encounter this issue myself. Perhaps you can send me an archive
of your project where you had to do this.

> I'll be waiting for a better solution for the futur, but for instance,
> this does the trick !
> Thank you for this great plugin !

:+1: Happy to hear it is working for you.

**Comment by aorfevre** [comment]
I'm already following this post : https://issues.apache.org/jira/browse/CB-8866 don't hesitate to communicate if there is any improvements concerning the implementation of this plugin for windows phone 8.1

**Comment by sachin123sharma** [comment]
Hi Chris,
Need one help (again).
 Please suggest how can we call "resume" and "pause" event (to check whether app is in foreground or background) in Windows Phone 8.1.

**Comment by brody2consult** [comment]
Do you mean you want to use the functionality from `cordova-plugin-background-mode` (https://github.com/katzer/cordova-plugin-background-mode) on Windows Phone 8.1, or do you mean something else?

**Comment by sachin123sharma** [comment]
Yes, we want to fire some event when app is resumed.

**Comment by brody2consult** [comment]
I can look at this tomorrow (busy with some other issues today).

**Comment by sachin123sharma** [comment]
Also I would like to know , if we have a plugin available for Pull to Refresh feature for Windows phone 8.0,windows phone 8.1 .

**Comment by front-a-little** [comment]
I've followed the instructions above to install https://github.com/litehelpers/Cordova-sqlite-storage to my project via Cordova CLI but when I build it for Win8.1 Phone via `cordova build windows` I get following error message:

> The processor architecture of your project 'neutral' doesn't match the processor architecture 'x86' of the referenced project 'SQLite3'

I understand the problem but can't find a way to tell Cordova to build this for x86 or is this related to my general setup ?

**Comment by brody2consult** [comment]
From [this comment in apache/cordova-windows/#67](https://github.com/apache/cordova-windows/pull/67#issuecomment-97033277)

> Here's the exact syntax:
> `cordova build windows -- --archs="x86"`

**Comment by d3orn** [comment]
Any news considering this problem? I am using the plugin on iOS and Android but now I need support for Windows. I want to build for my phone (currently for testing) but using plugman and the nufix is just time consuming because the rest of my app needs other plugins and I normally us the CLI. I tried building for x86 only but I get an error as soon as I try to openDatabase

**Comment by brody2consult** [comment]
If you build to run on your phone, you have to get the CPU architecture right (I _think_ most phones are `arm`). If you build to run on your development system, you have to select a matching CPU target (`x86` or `x86_64`). I am now testing with the newer Cordova CLI with no problems.

The "nufix" version has now fallen behind and I will either update or delete it.

I am closing this issue since it is old. If you continue to have problems please raise a new issue.

**Comment by bajajsu16** [comment]
Hi Brodybits,

Can you please help.

I am getting following error while trying to build my cordova windows app using visual studio 2015 Community version

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1189,5): error MSB3819: Cannot find assembly "C:\projectName\plugins\cordova-sqlite-storage\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\release\SQLite3.UWP\SQLite3.UWP.dll", which may contain managed resources that need to be included in this app package.  Please ensure that this assembly exists. [C:\projectNamw\platforms\windows\CordovaApp.Windows10.jsproj]
Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe: Command failed with exit code 1

**Comment by brody2consult** [comment]
@bajajsu16 the answer is already in README.md. In case anything is not clear please raise a new issue.
