### ISSUE TITLE
XCode build fails: Redefinition of enumerator 'SYNTAX_ERR'

### ISSUE THREAD

**Issue by ryaa** [brody2consult/cordova-sqlite-storage#868]
The error started to appear when I added the below cordova plugins to the project where cordova-sqlite-storage plugin already existed
- cordova-plugin-file
- cordova-plugin-qrscanner

The cordova-sqlite-storage plugin has WebSQLError enum with SYNTAX_ERR = 5 and cordova-plugin-file plugin has CDVFileError enum with SYNTAX_ERR = 8. It seems to be the problem with the same name for these enums.

**Comment by brody2consult** [comment]
It looks like `cordova-plugin-file` suddenly started using the `SYNTAX_ERR` enum; you should be able to use an older version of that plugin as a workaround. Should be fixed when I do SQLite 3.28.0 update (#867).

**Comment by digaus** [comment]
Any progress on this?

**Comment by brody2consult** [comment]
I hope to make this soon, please followup if I don't fix this in the next 1-2 weeks or so.

**Comment by brody2consult** [comment]
Should be fixed with a quick workaround in version 3.4.0. I will need some time to propagate this workaround update into the other SQLite plugin versions.

**Comment by digaus** [comment]
> Should be fixed with a quick workaround in version 3.4.0. I will need some time to propagate this workaround update into the other SQLite plugin versions.

Thanks will check soon :)

**Comment by digaus** [comment]
@brodybits it works with 3.4.0
